import type { Metadata } from "next";
import { GeistPixelLine } from "geist/font/pixel";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistPixelLine.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
      <Analytics />
    </html>
  );
}
